### ISSUE TITLE
Lack of APNS documentation and probable apns alert issue

### ISSUE THREAD

**Issue by mimikadze** [patientslikeme/firebase_cloud_messenger#6]
Lack of apns documentation. Had to read the codebase. Anyway get an error trying to send an alert via APNS.

```
message = {
  apns: { payload: { alert: { title: "title" }, badge: 2 } },
  token: "my_fcm_reg_id"
}

FirebaseCloudMessenger.send(message: message)

=> FirebaseCloudMessenger::BadRequest:       Status: 400

      Request contains an invalid argument.
```

as well as

```
notification = FirebaseCloudMessenger::Notification.new(title: "title")
apns_alert = FirebaseCloudMessenger::Apns::Alert.new(title: "title")
apns_payload = FirebaseCloudMessenger::Apns::Payload.new(alert: apns_alert, badge: 2)
apns_config = FirebaseCloudMessenger::Apns::Config.new(payload: apns_payload)

msg = FirebaseCloudMessenger::Message.new(name: "name",
                                          notification: notification,
                                          apns: apns_config,
                                          token: "my_fcm_reg_id")

       => 
FirebaseCloudMessenger::BadRequest:       Status: 400

      Request contains an invalid argument.
```

Correct me if I'm trying to send it the wrong way.

**Comment by vincedevendra** [comment]
Thanks for opening the issue! Running validations against the FCM api gives us a hint about what went wrong:

In the first case, let's instantiate a `FirebaseCloudMessenger::Message` with your `message` hash and run some validations against the FCM api to see what's going on:

```ruby
[26] pry(main)> m = FirebaseCloudMessenger::Message.new(message)
=> #<FirebaseCloudMessenger::Message:0x007fe78080a268>
[27] pry(main)> m.valid?(against_api: true)
=> false
[28] pry(main)> m.errors
=> [{"@type"=>"type.googleapis.com/google.rpc.BadRequest", "fieldViolations"=>[{"field"=>"message.apns.payload", "description"=>"Payload of Apple Push Notification Service must contain an [aps] key."}]},
 {"@type"=>"type.googleapis.com/google.firebase.fcm.v1.FcmError", "errorCode"=>"INVALID_ARGUMENT"}]
```

So the problem is that the message should look like this:
```ruby
message = {
  apns: {
    payload: {
      aps: {
        alert: {
          title: "title"
        },
        badge: 2 }
    }
  },
  token: "my_fcm_reg_id"
}

```
I'm assuming it's the same problem in the second case. The reason you forgot the `aps` key is because you correctly read my incorrect code. 😢 `FirebaseCloudMessenger::Apns::Payload` will need to be modified, as well as the json schema.

In the meantime, modifying your first example by sending the message hash above will work, since it will bypass the buggy `Payload` class.  Those data classes are meant to just be helpful, but are not really necessary at the end of the day.

As for documentation, I was relying on Google's own docs (https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message) to be clear, but I agree that's not ideal. I think it would be great to start a wiki for this project with a bunch of different examples, including for APNS.

Let me know if you'd like to contribute a patch or some docs. Otherwise, I should be able to devote some time to it this weekend or next week.
